// ──────────────────────────────────────────────────────────────────────────
// Orders — customer-side order creation.
//
// When a logged-in user places an order, we take a FROZEN snapshot of their
// latest saved album and insert it into the `orders` table. The insert runs
// under the customer's session, so RLS ("auth.uid() = user_id") authorizes it.
// The operator/fulfillment side reads these later via the backend (service_role).
// ──────────────────────────────────────────────────────────────────────────

import { supabase } from './supabase';

export interface ShippingDetails {
  name: string;
  phone: string;
  address: string;
}

export interface OrderSpecs {
  material: string;
  cover: string;
  size: string;
}

export interface CreatedOrder {
  id: string;
  order_number: string;
  status: string;
}

/**
 * Create an order for the given user by snapshotting their most recently
 * updated album. Throws a friendly Error if there's no album to order.
 */
export async function createOrderFromLatestAlbum(opts: {
  userId: string;
  specs: OrderSpecs;
  shipping: ShippingDetails;
  amount: number;
}): Promise<CreatedOrder> {
  // 1. Load the latest album to freeze into the order.
  const { data: albums, error: albErr } = await supabase
    .from('albums')
    .select('id, title, album_type, album_size, selected_template, photos_per_page, pages, photos, cover_photo')
    .eq('user_id', opts.userId)
    .order('updated_at', { ascending: false })
    .limit(1);

  if (albErr) throw new Error(`Could not load your album: ${albErr.message}`);
  const album = albums?.[0];
  if (!album) {
    throw new Error('No saved album found to order. Build and save an album first, then place your order.');
  }

  const pageCount = Array.isArray(album.pages) ? album.pages.length : 0;

  // 2. Insert the order. order_number + status are generated by the DB defaults.
  const { data, error } = await supabase
    .from('orders')
    .insert({
      user_id: opts.userId,
      album_id: album.id,
      album_snapshot: album, // frozen copy
      album_size: opts.specs.size,
      material: opts.specs.material,
      cover: opts.specs.cover,
      page_count: pageCount,
      amount: opts.amount,
      ship_name: opts.shipping.name,
      ship_phone: opts.shipping.phone,
      ship_address: opts.shipping.address,
      status_history: [{ status: 'pending_payment', at: new Date().toISOString() }],
    })
    .select('id, order_number, status')
    .single();

  if (error) throw new Error(`Could not place your order: ${error.message}`);
  return data as CreatedOrder;
}
