/* ── PSGC (Philippine Standard Geographic Code) lookups ────────────────────
   Data is served statically from public/psgc/ (generated by scripts/build-psgc.mjs
   from the @jobuntux/psgc devDependency). Fetched on demand — nothing here is in
   the JS bundle. Each fetch is cached for the session so cascading is instant
   after the first load. */

export interface PsgcItem { code: string; name: string; }
interface Region extends PsgcItem {}
export interface ProvinceItem extends PsgcItem { regCode: string; }
interface Muncity extends PsgcItem { provKey: string; }
interface Barangay extends PsgcItem { cityKey: string; }

// BASE_URL keeps this correct whether the app is served at "/" (Vercel) or a
// sub-path (GitHub Pages). HashRouter doesn't affect these absolute fetches.
const BASE = `${import.meta.env.BASE_URL}psgc/`;

const cache = new Map<string, Promise<unknown>>();
function loadJson<T>(file: string): Promise<T> {
  if (!cache.has(file)) {
    cache.set(
      file,
      fetch(BASE + file).then((r) => {
        if (!r.ok) throw new Error(`PSGC load failed (${r.status}): ${file}`);
        return r.json();
      }).catch((e) => { cache.delete(file); throw e; }),
    );
  }
  return cache.get(file) as Promise<T>;
}

/** All regions (small — loaded once). */
export const loadRegions = () => loadJson<Region[]>('regions.json');

/** Provinces within a region (regCode, e.g. "13"). */
export async function loadProvinces(regionCode: string): Promise<PsgcItem[]> {
  const all = await loadJson<ProvinceItem[]>('provinces.json');
  return all.filter((p) => p.regCode === regionCode);
}

/** Every province across all regions — each carries its regCode so the region
 *  can be derived once a province is chosen (the picker asks for province, not
 *  region). */
export const loadAllProvinces = () => loadJson<ProvinceItem[]>('provinces.json');

/** Cities/municipalities within a province (provinceCode = regCode+provCode). */
export async function loadCities(provinceCode: string): Promise<PsgcItem[]> {
  const all = await loadJson<Muncity[]>('muncities.json');
  return all.filter((m) => m.provKey === provinceCode);
}

/** Barangays within a city. Fetches only the selected province's barangay file
 *  (public/psgc/brgy/<provinceCode>.json) then filters to the chosen city. */
export async function loadBarangays(provinceCode: string, cityCode: string): Promise<PsgcItem[]> {
  const all = await loadJson<Barangay[]>(`brgy/${provinceCode}.json`);
  return all.filter((b) => b.cityKey === cityCode);
}
