/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        /* ── Brand tokens (pass 1 of the theme system) ─────────────────
           Each resolves to an RGB triplet in src/index.css so `/20`
           opacity modifiers work and a theme can redefine the value. */
        peach: "rgb(var(--t-peach) / <alpha-value>)",
        "blush-pink": "rgb(var(--t-blush-pink) / <alpha-value>)",
        dark: "rgb(var(--t-dark) / <alpha-value>)",
        medium: "rgb(var(--t-medium) / <alpha-value>)",
        light: "rgb(var(--t-light) / <alpha-value>)",
        taupe: "rgb(var(--t-taupe) / <alpha-value>)",
        "ink-warm": "rgb(var(--t-ink-warm) / <alpha-value>)",
        "ink-mid": "rgb(var(--t-ink-mid) / <alpha-value>)",
        charcoal: "rgb(var(--t-charcoal) / <alpha-value>)",
        cocoa: "rgb(var(--t-cocoa) / <alpha-value>)",
        stone: "rgb(var(--t-stone) / <alpha-value>)",
        cream: "rgb(var(--t-cream) / <alpha-value>)",
        "warm-white": "rgb(var(--t-warm-white) / <alpha-value>)",
        blush: "rgb(var(--t-blush) / <alpha-value>)",
        "blush-deep": "rgb(var(--t-blush-deep) / <alpha-value>)",
        sand: "rgb(var(--t-sand) / <alpha-value>)",
        "sand-deep": "rgb(var(--t-sand-deep) / <alpha-value>)",
        line: "rgb(var(--t-line) / <alpha-value>)",
        "line-soft": "rgb(var(--t-line-soft) / <alpha-value>)",
        paper: "rgb(var(--t-paper) / <alpha-value>)",
        success: "rgb(var(--t-success) / <alpha-value>)",
        rust: "rgb(var(--t-rust) / <alpha-value>)",
        "rust-deep": "rgb(var(--t-rust-deep) / <alpha-value>)",
        "coral-soft": "rgb(var(--t-coral-soft) / <alpha-value>)",
        "soft-lavender": "rgb(var(--t-soft-lavender) / <alpha-value>)",
        mint: "rgb(var(--t-mint) / <alpha-value>)",
        "sky-blue": "rgb(var(--t-sky-blue) / <alpha-value>)",
        "cream-gold": "rgb(var(--t-cream-gold) / <alpha-value>)",
        "soft-sage": "rgb(var(--t-soft-sage) / <alpha-value>)",
        "pale-peach": "rgb(var(--t-pale-peach) / <alpha-value>)",
        "pale-coral": "rgb(var(--t-pale-coral) / <alpha-value>)",
        lavender: "#E8E0F0",
        mist: "#E0E8F0",
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body: ['"DM Sans"', 'sans-serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        "2xl": "16px",
        "3xl": "24px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        card: "0 2px 12px rgba(45,45,45,0.06)",
        "card-hover": "0 8px 32px rgba(45,45,45,0.1)",
        button: "0 2px 8px rgba(244,194,161,0.3)",
        "button-hover": "0 4px 16px rgba(244,194,161,0.4)",
        dropdown: "0 8px 24px rgba(45,45,45,0.08)",
        "builder-panel": "0 0 20px rgba(45,45,45,0.06)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "bounce-gentle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(8px)" },
        },
        "ken-burns": {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(1.05)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "bounce-gentle": "bounce-gentle 2s ease-in-out infinite",
        "ken-burns": "ken-burns 15s ease-in-out infinite alternate",
        "float": "float 8s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
