/* ══════════════════════════════════════════════════════════════════════════
   QUOTE BANK — the pre-loaded caption lines (owner, 2026-10-02: "100 pre
   loaded quotes of each category … write them for me and get free ones").

   100 lines for each occasion customers pick (Wedding, Baptism, Birthday,
   Baby, Graduation, Family, Vacation) plus the general set. Megy deals from
   these FIRST, with no AI call (lib/quotes.ts); the AI only writes extras an
   album needs beyond them. Every album shuffles its own pick, never repeats.

   Rules for every line: at most 46 characters (it must print cleanly), no
   quotation marks, no emoji, no trailing full stop. Most are original lines
   written for Megy Prints; the rest are PUBLIC DOMAIN — scripture in the
   King James Version / World English Bible, authors who died long ago,
   traditional rhymes and vows — each named in PUBLIC_DOMAIN_SOURCES, and
   each checked word-for-word against its source. Never add a song lyric, a
   film line or a quote by a modern author: albums are a paid product.
   ══════════════════════════════════════════════════════════════════════════ */

import type { TemplateType } from './types';

export const QUOTE_BANK: Record<TemplateType, string[]> = {
  // Wedding — 100 lines
  wedding: [
    'Two hearts, one journey',
    'Forever starts today',
    'To have and to hold', // public domain: Book of Common Prayer, marriage vows (1662)
    'Love wrote this story',
    'Together is a beautiful place',
    'The beginning of always',
    'Till death us do part', // public domain: Book of Common Prayer, marriage vows (1662)
    'For better, for worse', // public domain: Book of Common Prayer, marriage vows (1662)
    'To love and to cherish', // public domain: Book of Common Prayer, marriage vows (1662)
    'Grow old along with me! The best is yet to be', // public domain: Robert Browning, Rabbi Ben Ezra (1864)
    'Love is patient and is kind', // public domain: 1 Corinthians 13:4, World English Bible
    'Love never fails', // public domain: 1 Corinthians 13:8, World English Bible
    'Two are better than one', // public domain: Ecclesiastes 4:9, King James Version
    'A threefold cord is not quickly broken', // public domain: Ecclesiastes 4:12, King James Version
    'Whither thou goest, I will go', // public domain: Ruth 1:16, King James Version
    'Set me as a seal upon thine heart', // public domain: Song of Solomon 8:6, King James Version
    'Many waters cannot quench love', // public domain: Song of Solomon 8:7, King James Version
    'I am my beloved\'s, and my beloved is mine', // public domain: Song of Solomon 6:3, King James Version
    'How do I love thee? Let me count the ways', // public domain: Elizabeth Barrett Browning, Sonnet 43 (1850)
    'Come live with me and be my love', // public domain: Christopher Marlowe, The Passionate Shepherd to His Love (1599)
    'What therefore God hath joined together', // public domain: Mark 10:9, King James Version
    'My bounty is as boundless as the sea', // public domain: Shakespeare, Romeo and Juliet, Act 2 Scene 2 (1597)
    'Something old, something new', // public domain: Traditional English wedding rhyme (19th c.)
    'Something borrowed, something blue', // public domain: Traditional English wedding rhyme (19th c.)
    'Today, tomorrow, always',
    'My favorite person to come home to',
    'Here\'s to us',
    'And so we begin',
    'I choose you, every day',
    'My forever person',
    'Hand in hand, heart to heart',
    'Our love story, chapter one',
    'Two souls, one home',
    'The day we said yes',
    'Mr. and Mrs., forever',
    'Love is the best adventure',
    'Happily ever after starts here',
    'With this ring, my heart',
    'Bound by love, blessed by God',
    'In His time, He made us one',
    'A promise kept for a lifetime',
    'Love, laughter, and forever',
    'Yours, always',
    'Side by side, through it all',
    'Our hearts said yes first',
    'Love found its way home',
    'One love, one life, one home',
    'Married to my best friend',
    'Just married',
    'Gentle love, steady hands',
    'Where you are is home',
    'Every day with you is a gift',
    'Two families, one love',
    'You and me, always',
    'The vows we will keep',
    'Grace brought us together',
    'A lifetime of little moments',
    'Love beyond measure',
    'The happiest of beginnings',
    'Our sweetest yes',
    'Written in the stars, sealed in faith',
    'The first page of forever',
    'Love that grows with every year',
    'Through every season, together',
    'A love we will tell our grandkids about',
    'Love, honor, and laughter',
    'Our first day as a family of two',
    'Every kiss a promise',
    'Faithful hearts, joyful home',
    'The moment I knew it was you',
    'Two names, one story',
    'A love worth celebrating',
    'Forever looks good on us',
    'Blessed in our union',
    'Joined by love, kept by grace',
    'Love is in every detail',
    'The adventure of us',
    'Love made us brave',
    'Our hearts, one rhythm',
    'Your hand in mine, forever',
    'We found our forever',
    'Happiness, shared',
    'Love, our greatest gift',
    'Your laugh is my sweetest song',
    'The day love said always',
    'A covenant of the heart',
    'Together, we are whole',
    'To many years of us',
    'Blessed by family, joined before God',
    'Life is sweeter with you',
    'Two lives woven into one',
    'Dancing into our new life',
    'May our home be full of joy',
    'Building a home on love',
    'We said I do',
    'My heart knows its way to you',
    'A love to last all our days',
    'Two hearts, one faith',
    'Your love is my favorite place',
    'Cheers to the newlyweds',
  ],
  // Baptism — 100 lines
  baptism: [
    'Child of God',
    'Washed in grace',
    'A new beginning in faith',
    'Blessed and beloved',
    'Held in His hands',
    'Let the little children come',
    'Suffer the little children to come unto me', // public domain: Mark 10:14, King James Version
    'For of such is the kingdom of God', // public domain: Mark 10:14, King James Version
    'The Lord bless thee, and keep thee', // public domain: Numbers 6:24, King James Version
    'The Lord make his face shine upon thee', // public domain: Numbers 6:25, King James Version
    'I have called thee by thy name; thou art mine', // public domain: Isaiah 43:1, King James Version
    'For he shall give his angels charge over thee', // public domain: Psalm 91:11, King James Version
    'The Lord is my shepherd; I shall not want', // public domain: Psalm 23:1, King James Version
    'Ye are the light of the world', // public domain: Matthew 5:14, King James Version
    'Let your light so shine before men', // public domain: Matthew 5:16, King James Version
    'Born of water and of the Spirit', // public domain: John 3:5, King James Version
    'A new heart also will I give you', // public domain: Ezekiel 36:26, King James Version
    'Peace be unto you', // public domain: John 20:19, King James Version
    'Thy word is a lamp unto my feet', // public domain: Psalm 119:105, King James Version
    'The Lord is my light and my salvation', // public domain: Psalm 27:1, King James Version
    'Lo, I am with you alway', // public domain: Matthew 28:20, King James Version
    'God is love', // public domain: 1 John 4:8, King James Version
    'We love him, because he first loved us', // public domain: 1 John 4:19, King James Version
    'Grace upon grace', // public domain: John 1:16, World English Bible
    'Safe in the arms of Jesus', // public domain: Fanny Crosby, hymn (1868)
    'Jesus loves me, this I know', // public domain: Anna Bartlett Warner, poem in Say and Seal (1860)
    'Baptized in love',
    'A child of light',
    'Welcomed into God\'s family',
    'Sealed with His love',
    'Blessed with water and grace',
    'Wrapped in His love',
    'Precious in His sight',
    'Our little one, His beloved',
    'Faith, hope, and a little one',
    'Today you became His',
    'Safe under His wings',
    'A blessed beginning',
    'Little lamb in the Shepherd\'s care',
    'Born of love, renewed in grace',
    'Surrounded by love and prayer',
    'Faith planted, love to grow',
    'God\'s gift to our family',
    'The day heaven smiled on you',
    'A soul made new',
    'Marked with oil, filled with grace',
    'May Mama Mary keep you close',
    'Little heart, big faith',
    'A new name in His book',
    'May His light guide your way',
    'Raised in faith, held by love',
    'A blessing to us all',
    'Today, a child of the Church',
    'Grow in wisdom and in grace',
    'Blessed with every prayer',
    'Grace poured out like water',
    'We promise to guide you to Him',
    'Faith is our first gift to you',
    'Clothed in white, wrapped in grace',
    'A candle lit for your path',
    'Light of Christ, shine in you',
    'Tiny hands folded in prayer',
    'God\'s promise in a tiny heart',
    'Holy water, happy tears',
    'Our parish family grows by one',
    'Prayers whispered, love declared',
    'Chosen, cherished, and baptized',
    'Godchild, God\'s child',
    'May angels watch over you',
    'Rooted in faith from the start',
    'In the name of the Father',
    'A heart for God, a life of love',
    'Named before God and His people',
    'Heaven rejoices today',
    'You belong to God and to us',
    'One little soul, much rejoicing',
    'Touched by holy water',
    'God knew you first',
    'Your journey of faith begins',
    'Showered with blessings',
    'Little saint in the making',
    'Grace, in the smallest form',
    'Cradled by us, blessed by Him',
    'Signed with the cross of Christ',
    'Love that will never let go',
    'A child of the promise',
    'Strong in faith, gentle in love',
    'The Church welcomes you with joy',
    'A day of grace for our family',
    'Holy and loved',
    'Blessed waters, blessed child',
    'Kept by His grace forever',
    'A gift from above',
    'Our prayers, answered',
    'Born to shine His light',
    'Sweet child of grace',
    'Grace for your every step',
    'Godparents, guides, and blessings',
    'Pure, precious, and promised to God',
    'With water and with Spirit',
  ],
  // Birthday (incl. debut) — 100 lines
  birthday: [
    'Another year of wonderful',
    'Make a wish',
    'Today we celebrate you',
    'Cheers to you',
    'The best is yet to come',
    'Let the good times roll',
    'Many happy returns of the day', // public domain: Traditional birthday greeting (18th c.)
    'With mirth and laughter let old wrinkles come', // public domain: Shakespeare, The Merchant of Venice, Act 1 Scene 1 (1600)
    'Age is opportunity no less than youth itself', // public domain: Henry Wadsworth Longfellow, Morituri Salutamus (1875)
    'Gather ye rosebuds while ye may', // public domain: Robert Herrick, To the Virgins, to Make Much of Time (1648)
    'Laugh, and the world laughs with you', // public domain: Ella Wheeler Wilcox, Solitude (1883)
    'A merry heart doeth good like a medicine', // public domain: Proverbs 17:22, King James Version
    'This is the day which the Lord hath made', // public domain: Psalm 118:24, King James Version
    'So teach us to number our days', // public domain: Psalm 90:12, King James Version
    'Monday\'s child is fair in face', // public domain: Traditional rhyme, A. E. Bray, Traditions of Devonshire (1838)
    'Live while you live', // public domain: Philip Doddridge, epigram on Dum vivimus, vivamus (18th c.)
    'Cake for everyone, wishes for you',
    'Here\'s to another trip around the sun',
    'Older, wiser, more wonderful',
    'Celebrate every candle',
    'Another chapter, another adventure',
    'You make every year brighter',
    'Cake, candles, and love',
    'Born to sparkle',
    'A year older, a year bolder',
    'Blow out the candles, dream big',
    'The day the world got brighter',
    'Celebrating the wonder of you',
    'Wishes do come true',
    'To many more birthdays together',
    'Hip hip hooray',
    'Today is all about you',
    'Another year of making memories',
    'Smiles, cake, and candlelight',
    'Confetti, cake, and family',
    'You are worth celebrating',
    'Aged to perfection',
    'Forever young at heart',
    'Count the memories, not the years',
    'Sweet as cake, bright as candles',
    'Blessed with another year',
    'Laughter is the best gift',
    'Turning the page with a smile',
    'A toast to the birthday star',
    'Still the life of the party',
    'One more year of you',
    'Sing loud, it\'s your birthday',
    'Here\'s to the years ahead',
    'Here comes the birthday parade',
    'Big dreams, bigger cake',
    'Balloons up, worries down',
    'Your day, your way',
    'Wishing you the sweetest year',
    'Sprinkled with joy',
    'Little candles, big wishes',
    'Born on a beautiful day',
    'Twelve months of blessings',
    'Eighteen and blooming',
    'Eighteen roses, one dream',
    'A lifetime of birthdays, all blessed',
    'Golden years, golden hearts',
    'Decades of joy, and counting',
    'Still growing, still glowing',
    'May all your wishes take flight',
    'The party starts with you',
    'One candle closer to wisdom',
    'Love grows with every year',
    'Happy heart, happy birthday',
    'Make it a year to remember',
    'Surrounded by the ones who love you',
    'You light up the room',
    'Shine on, birthday star',
    'Cheers to the next chapter',
    'Wish big, laugh loud',
    'Candles glowing, hearts too',
    'Thankful for the day you were born',
    'One year wiser, still young',
    'The gift of you',
    'Pancit for a long, happy life',
    'All the joy this year can hold',
    'Party hats and happy hearts',
    'The year ahead is yours',
    'Celebrate the little things',
    'Cake first, then everything else',
    'Years well spent, more to come',
    'Making wishes with you',
    'Better with every candle',
    'Gifts unwrapped, hearts wide open',
    'Blessings on your special day',
    'Sweet celebrations',
    'Your best year yet',
    'Laughing through the years',
    'Birthday magic',
    'The cake is just the beginning',
    'More candles, more love',
    'The whole barkada came for you',
    'Balloons, games, and handaan',
    'A day as special as you',
    'A day for hugs and happy tears',
    'Happy birthday, with all our love',
  ],
  // Baby — 100 lines
  baby: [
    'Welcome to the world, little one',
    'Tiny hands, full hearts',
    'Our greatest adventure',
    'Worth the wait',
    'So small, so loved',
    'Sweet dreams, little dreamer',
    'For this child I prayed', // public domain: 1 Samuel 1:27, King James Version
    'Lo, children are an heritage of the Lord', // public domain: Psalm 127:3, King James Version
    'I am fearfully and wonderfully made', // public domain: Psalm 139:14, King James Version
    'Before I formed thee in the belly I knew thee', // public domain: Jeremiah 1:5, King James Version
    'Twinkle, twinkle, little star', // public domain: Jane Taylor, The Star, in Rhymes for the Nursery (1806)
    'Sleepy smiles and soft blankets',
    'Rock-a-bye baby, on the treetop', // public domain: Traditional nursery rhyme (Mother Goose's Melody, c. 1765)
    'Out of the everywhere into here', // public domain: George MacDonald, Baby, in At the Back of the North Wind (1871)
    'Heaven lies about us in our infancy', // public domain: William Wordsworth, Intimations of Immortality (1807)
    'Trailing clouds of glory do we come', // public domain: William Wordsworth, Intimations of Immortality (1807)
    'Sleep, baby, sleep', // public domain: Traditional lullaby, English words by Elizabeth Prentiss (d. 1878)
    'Star light, star bright', // public domain: Traditional nursery rhyme (in print by 1866)
    'Sweet dreams, form a shade', // public domain: William Blake, A Cradle Song, Songs of Innocence (1789)
    'Hello, little love',
    'Ten tiny fingers, ten tiny toes',
    'The newest member of our hearts',
    'Our little miracle',
    'Love at first sight, truly',
    'You made us a family',
    'Small wonder, big love',
    'The sweetest hello',
    'Little feet, big footprints',
    'Born and adored',
    'Our hearts are fuller than ever',
    'Snuggles and sweet dreams',
    'Every yawn, every smile',
    'Fresh from heaven',
    'You light up our days',
    'Tiny but mighty',
    'First breath, first love',
    'So much love in so little you',
    'A dream we held for so long',
    'Welcome home, little one',
    'Full tummy, happy baby',
    'Cuddles are our new favorite',
    'Small hands, big hugs',
    'Heartbeat of our home',
    'Little blessing, big joy',
    'The smallest one runs the house',
    'Baby\'s first everything',
    'Sleepy eyes, sweet sighs',
    'Our new favorite person',
    'Brand new and perfectly you',
    'Loved before you were born',
    'Wonder in a tiny bundle',
    'Giggles, coos, and lullabies',
    'Our little dream come true',
    'Tiny toes, endless love',
    'Every day you grow, so do we',
    'Freshly arrived, deeply loved',
    'Our world just got sweeter',
    'Little you, big adventure',
    'Soft cheeks, warm hearts',
    'Counting fingers, counting blessings',
    'One little heartbeat changed everything',
    'The best gift we ever got',
    'Little sprout, growing strong',
    'Made with love, held with care',
    'Our pride and our joy',
    'Dreams come in tiny sizes',
    'You are our happy place',
    'Hush now, you are home',
    'First smile, forever ours',
    'Precious little soul',
    'Wrapped in love from day one',
    'Baby bliss',
    'Sweetest little heartbeat',
    'Born to be loved',
    'A tiny heart, a giant love',
    'Our hearts belong to you now',
    'Born into a world of love',
    'The newest little star',
    'Peekaboo, we love you',
    'Bundle of joy',
    'Little fingers hold big love',
    'Long-awaited and dearly loved',
    'Life\'s sweetest beginning',
    'Our family just grew by one',
    'Every coo is a song',
    'You complete our story',
    'Welcome, sweet baby',
    'Rocked in love every night',
    'Button nose, bright eyes',
    'Our first look at forever',
    'Forever our baby',
    'Gentle hands, gentle heart',
    'Heaven sent, held close at home',
    'Mama\'s heart, Papa\'s pride',
    'The cutest chapter yet',
    'A little soul with a big laugh',
    'Bath time and bubbles',
    'Every day, a new discovery',
    'Welcome to our arms',
    'The beginning of our forever',
  ],
  // Graduation — 100 lines
  graduation: [
    'The tassel was worth the hassle',
    'Off to make your mark',
    'The future is bright',
    'And so the adventure begins',
    'Dream big, work hard',
    'This is just the beginning',
    'Hitch your wagon to a star', // public domain: Ralph Waldo Emerson, Civilization, in Society and Solitude (1870)
    'Knowledge is power', // public domain: Proverb, after Francis Bacon's Latin, Meditationes Sacrae (1597)
    'Ad astra per aspera', // public domain: Latin motto: to the stars through difficulties
    'Wisdom is the principal thing', // public domain: Proverbs 4:7, King James Version
    'I can do all things through Christ', // public domain: Philippians 4:13, King James Version
    'Be strong and of a good courage', // public domain: Joshua 1:9, King James Version
    'Tomorrow to fresh woods, and pastures new', // public domain: John Milton, Lycidas (1638)
    'To strive, to seek, to find, and not to yield', // public domain: Alfred Tennyson, Ulysses (1842)
    'Let us, then, be up and doing', // public domain: Henry Wadsworth Longfellow, A Psalm of Life (1838)
    'Act well your part, there all the honour lies', // public domain: Alexander Pope, An Essay on Man (1734)
    'The world was all before them', // public domain: John Milton, Paradise Lost (1667)
    'Caps off to you',
    'Proud of every step it took',
    'Diploma in hand, dreams in heart',
    'Late nights, bright futures',
    'The world is waiting for you',
    'We did it!',
    'Class dismissed, future begins',
    'Now go change the world',
    'Hard work pays off',
    'Toss the cap, chase the dream',
    'One chapter ends, another begins',
    'Ready for what\'s next',
    'Learned, earned, and celebrated',
    'Brains, heart, and a diploma',
    'Onward and upward',
    'The best is still ahead',
    'Proud family, prouder graduate',
    'Years of effort, one proud day',
    'The finish line is a starting line',
    'Mabuhay, graduate!',
    'Faith, family, and a diploma',
    'You earned every bit of this',
    'Here\'s to the next adventure',
    'Brighter days ahead',
    'Making our family proud',
    'Scholar, dreamer, graduate',
    'From school bags to big dreams',
    'A tassel turned, a door opened',
    'From first day to final march',
    'Your future starts now',
    'Lessons learned, dreams unlocked',
    'Walk proud, graduate',
    'A milestone worth every sacrifice',
    'Worth every baon and every fare',
    'Mom and Dad, this is for you',
    'For the parents who prayed',
    'Every book, every exam, worth it',
    'Knowledge gained, horizons wide',
    'Today a graduate, tomorrow a leader',
    'Proudly finished',
    'Stepping into tomorrow',
    'The sky\'s the limit',
    'Keep learning, keep growing',
    'Done with school, not with dreams',
    'They called your name, and we cheered',
    'Wings ready, world wide open',
    'Congratulations, graduate',
    'Celebrating the scholar in you',
    'Goodbye classroom, hello world',
    'Hard-won and well-deserved',
    'Commencement means beginning',
    'From learning to leading',
    'Your story is just getting good',
    'Determined, dedicated, done',
    'A dream fulfilled at last',
    'Grateful for every teacher',
    'Go share what you learned',
    'Head high, heart full',
    'Answered prayers in a toga',
    'Moving the tassel, moving forward',
    'Smart, strong, and unstoppable',
    'Next stop: everywhere',
    'Built by books and believing',
    'Celebrating years of hard work',
    'A future as bright as you',
    'Bold steps begin today',
    'Proof that dreams take work',
    'The road ahead is yours',
    'Honored, humbled, happy',
    'Class of forever',
    'Write the next chapter boldly',
    'Proud of who you became along the way',
    'To the teachers who believed',
    'Every lesson led to this',
    'May your next steps be blessed',
    'We are so proud of you',
    'You made it, graduate',
    'Go far, graduate',
    'Ready, set, graduate',
    'Today belongs to you',
    'Diploma earned, family overjoyed',
    'Pride in every page',
    'Built for big things',
  ],
  // Family — 100 lines
  family: [
    'Home is where our story begins',
    'Together is our favorite place',
    'Love is the heart of our family',
    'Gathered with grateful hearts',
    'The days we will remember',
    'Where life begins and love never ends',
    'Home is where the heart is', // public domain: Proverb (19th century)
    'There\'s no place like home', // public domain: John Howard Payne, Home! Sweet Home!, from the opera Clari (1823)
    'Mid pleasures and palaces though we may roam', // public domain: John Howard Payne, Home! Sweet Home!, from the opera Clari (1823)
    'Honour thy father and thy mother', // public domain: Exodus 20:12, King James Version
    'Children\'s children are the crown of old men', // public domain: Proverbs 17:6, King James Version
    'Behold, how good and how pleasant it is', // public domain: Psalm 133:1, King James Version
    'Her children arise up, and call her blessed', // public domain: Proverbs 31:28, King James Version
    'As for me and my house, we will serve the Lord', // public domain: Joshua 24:15, King James Version
    'Train up a child in the way he should go', // public domain: Proverbs 22:6, King James Version
    'Where we love is home', // public domain: Oliver Wendell Holmes Sr., Homesick in Heaven (1872)
    'The family is one of nature\'s masterpieces', // public domain: George Santayana, The Life of Reason: Reason in Society (1905)
    'Blood is thicker than water', // public domain: Proverb (in English print by 1789)
    'Merienda and long stories',
    'Firmly planted, free to grow',
    'Gathered around the same table',
    'Love around every corner',
    'Sunday lunches and big hugs',
    'Lolo and Lola\'s legacy of love',
    'Generations of love',
    'Our crew, our home',
    'Together is enough',
    'Family first, always',
    'Laughter is our love language',
    'Built on love, held by faith',
    'Our circle of love',
    'Home is wherever we are together',
    'The more, the merrier',
    'Cousins: friends for life',
    'Siblings by blood, friends by choice',
    'Family is a gift that lasts forever',
    'Roots deep, branches wide',
    'Every reunion, a celebration',
    'Love passed down through the years',
    'A home full of hearts',
    'Our greatest treasure is us',
    'Video calls and homecomings',
    'Miles apart, hearts together',
    'Balikbayan hearts, home at last',
    'Big family, bigger love',
    'Saying grace, sharing plates',
    'Mom\'s kitchen, Dad\'s jokes',
    'Lola\'s cooking, Lolo\'s stories',
    'Thankful for every one of you',
    'Love grows best at home',
    'The heart of our home',
    'Moments with the ones we love',
    'Our family, our blessing',
    'Rooted in love, growing in grace',
    'Laughter, love, and leftovers',
    'The table is always full',
    'Family stories, told and retold',
    'A legacy of love and faith',
    'Growing up, growing closer',
    'Nothing beats family time',
    'Together through every season',
    'Tito, Tita, and all the cousins',
    'Home is our favorite adventure',
    'Family: our first friends',
    'One family, many hearts',
    'Love lives here',
    'Three generations, one heart',
    'Old photos, new memories',
    'Every face, a reason to smile',
    'Ours to hold, now and always',
    'Our home, our haven',
    'Blessed to be us',
    'Love spoken in every language',
    'Making memories, side by side',
    'The ones who know us best',
    'Noche Buena at Lola\'s house',
    'Together we laugh, together we grow',
    'Holding on to what matters',
    'Love that fills the whole house',
    'Sharing life, sharing love',
    'We are better together',
    'Our family, kept by prayer',
    'Hugs that feel like home',
    'Hearts at home',
    'The joy of being together',
    'Forever grateful for family',
    'Our favorite people',
    'Love holds us together',
    'Cherished moments with family',
    'Same old jokes, same old love',
    'Family dinners and long talks',
    'Happiness is homemade',
    'Love without end',
    'Memories we keep forever',
    'A weekend with our favorites',
    'Childhood home, endless love',
    'The best of us is family',
    'All of us, together again',
    'Sweet home, sweet family',
    'Love is our family recipe',
  ],
  // Vacation (travel) — 100 lines
  travel: [
    'Adventure awaits',
    'Richer in moments than in luggage',
    'Wander often, wonder always',
    'Loving every stop along the way',
    'Make memories everywhere',
    'Born to explore',
    'Afoot and light-hearted', // public domain: Walt Whitman, Song of the Open Road (1856)
    'Travel is fatal to prejudice', // public domain: Mark Twain, The Innocents Abroad (1869)
    'I travel not to go anywhere, but to go', // public domain: Robert Louis Stevenson, Travels with a Donkey (1879)
    'The world\'s mine oyster', // public domain: Shakespeare, The Merry Wives of Windsor, Act 2 Scene 2 (1623)
    'The sea! the sea! the open sea!', // public domain: Barry Cornwall, The Sea, in English Songs (1832)
    'Over the hills and far away', // public domain: Traditional English song (in print by 1728)
    'The heavens declare the glory of God', // public domain: Psalm 19:1, King James Version
    'The mountains are calling and I must go', // public domain: John Muir, letter to his sister (1873; published 1924)
    'We came, we saw, we snacked',
    'Sun, sand, and sweet memories',
    'Island time, all the time',
    'Salty hair, happy hearts',
    'Same sky, new places',
    'Out of office, into adventure',
    'Passport full, heart fuller',
    'Sunny days and sandy feet',
    'Chasing sunsets together',
    'Beach days are the best days',
    'Somewhere new, together',
    'Vacation mode: on',
    'Sea you soon',
    'Paradise found',
    'Toes in the sand, heart at ease',
    'Road trips and good company',
    'Halo-halo under the sun',
    'Every kilometer, a new story',
    'Wanderlust and window seats',
    'Making waves together',
    'Breathe in the ocean air',
    'Where the road takes us',
    'Seven thousand islands, one heart',
    'Island hopping, heart happy',
    'Sunrise somewhere beautiful',
    'Postcards from our hearts',
    'The view was worth the climb',
    'Adventure is a family tradition',
    'Lost in the best way',
    'New places, old friends',
    'Sunkissed and smiling',
    'Waves, wind, and wonder',
    'Our favorite detour',
    'Souvenirs of the heart',
    'Exploring is our love language',
    'Far from home, close to each other',
    'A suitcase full of memories',
    'Every trip tells a story',
    'Golden hour, golden memories',
    'Salt air and sunshine',
    'Weekend getaway, forever memory',
    'Where the sea meets the sky',
    'Footprints on new shores',
    'Off the map, into the moment',
    'Crystal water, carefree days',
    'The ocean is our happy place',
    'Camping under a million stars',
    'Rain or shine, we explore',
    'Taking the scenic route',
    'Hello, sunshine',
    'Window seat, wide eyes',
    'Fresh air, fresh start',
    'Packed bags, open hearts',
    'Somewhere between here and there',
    'Adventures with my favorite people',
    'Mountain air and quiet hearts',
    'Exploring God\'s wonders',
    'Long summer days, short worries',
    'Bangka rides and blue lagoons',
    'Sky painted orange, just for us',
    'Here for the views',
    'Better together, everywhere',
    'Map in hand, joy in heart',
    'Sea breeze, easy days',
    'Making the world our home',
    'A trip to remember',
    'Lakes, peaks, and good company',
    'Holiday hearts',
    'Off we go',
    'Beyond the horizon',
    'Wild places, warm hearts',
    'Travel light, live fully',
    'Adventure looks good on us',
    'Kilometers of smiles',
    'Under the same stars',
    'The world is wide and wonderful',
    'A shared road is a shorter road',
    'Always one more place to see',
    'Every sunset, a promise',
    'Wanderers at heart',
    'Moments by the shore',
    'Weekend wanderers',
    'Bright skies, open roads',
    'Escape to somewhere lovely',
    'Snapshots from the road',
    'Coming home with stories',
  ],
  // General: any occasion the bank does not recognise — 100 lines
  classic: [
    'Cherished moments',
    'Timeless and true',
    'A story worth telling',
    'Moments to treasure',
    'Always a smile in these pages',
    'Some moments last a lifetime',
    'A thing of beauty is a joy for ever', // public domain: John Keats, Endymion (1818)
    'To every thing there is a season', // public domain: Ecclesiastes 3:1, King James Version
    'Hope is the thing with feathers', // public domain: Emily Dickinson, Hope, Poems: Second Series (1891)
    'This above all: to thine own self be true', // public domain: Shakespeare, Hamlet, Act 1 Scene 3 (1604)
    'Beauty is truth, truth beauty', // public domain: John Keats, Ode on a Grecian Urn (1820)
    'Carpe diem', // public domain: Horace, Odes 1.11 (23 BC)
    'What\'s past is prologue', // public domain: Shakespeare, The Tempest, Act 2 Scene 1 (1623)
    'Well done is better than well said', // public domain: Benjamin Franklin, Poor Richard's Almanack (1737)
    'One today is worth two tomorrows', // public domain: Benjamin Franklin, The Way to Wealth (1758)
    'Rejoice evermore', // public domain: 1 Thessalonians 5:16, King James Version
    'In every thing give thanks', // public domain: 1 Thessalonians 5:18, King James Version
    'Love all, trust a few, do wrong to none', // public domain: Shakespeare, All's Well That Ends Well, Act 1 Scene 1 (1623)
    'How far that little candle throws his beams!', // public domain: Shakespeare, The Merchant of Venice (1600)
    'Earth\'s crammed with heaven', // public domain: Elizabeth Barrett Browning, Aurora Leigh, Book VII (1856)
    'Every hour of the light and dark is a miracle', // public domain: Walt Whitman, Miracles, Leaves of Grass
    'Joy delights in joy', // public domain: Shakespeare, Sonnet 8 (1609)
    'All\'s well that ends well', // public domain: Proverb; Shakespeare play title (1605)
    'Make hay while the sun shines', // public domain: Proverb (in print by 1744)
    'It was the best of times', // public domain: Charles Dickens, A Tale of Two Cities (1859)
    'Count your blessings', // public domain: Johnson Oatman Jr., hymn Count Your Blessings (1897)
    'Here\'s to the good times',
    'Memories made together',
    'Captured with love',
    'A day to remember',
    'Smiles worth keeping',
    'Little moments, lasting joy',
    'Grateful for today',
    'Days worth remembering',
    'Life, beautifully ours',
    'Happier because we shared it',
    'Together, we made it',
    'Good friends, good memories',
    'Laughter fills these pages',
    'Every photo holds a story',
    'Small joys, saved for later',
    'Hearts full, cameras ready',
    'Moments that matter',
    'A season to remember',
    'Here, now, together',
    'Worth every smile',
    'The good stuff',
    'Celebrating milestones',
    'With gratitude and joy',
    'Proof of how happy we are',
    'A page from our story',
    'Old friends, new stories',
    'Made of moments like these',
    'Kept close, held dear',
    'Happy hearts, bright days',
    'Friends who feel like family',
    'A memory for every smile',
    'The joy is in the journey',
    'Thankful for these memories',
    'Blessed and grateful',
    'Snapshots of happiness',
    'Laughter, love, and light',
    'Good days, one after another',
    'Long talks and lazy afternoons',
    'Look how far we\'ve come',
    'Hold on to these days',
    'Life\'s little celebrations',
    'The heart remembers',
    'Brighter together',
    'Golden days',
    'Moments we\'ll never forget',
    'Sharing smiles across the years',
    'To good days and better ones',
    'Where memories live',
    'Every chapter worth reading',
    'We were here, and it was good',
    'Time well spent',
    'Joy in the everyday',
    'From our hearts to these pages',
    'Never forget how this felt',
    'A collection of happy days',
    'In good company',
    'Slow down, savor this',
    'Our kind of happy',
    'Making every moment count',
    'Let this moment stay',
    'Cheers to the memories',
    'All the best days',
    'Faces we love',
    'Happiness looks like this',
    'Today a memory, tomorrow a treasure',
    'Forever grateful',
    'Sunlight, smiles, and good friends',
    'Good times, great people',
    'Memories in the making',
    'Caught mid-laugh',
    'Every moment, a gift',
    'Stories we\'ll tell for years',
    'Click, smile, keep forever',
    'Here\'s to more days like this',
  ],
  // kept from before — reached only by typed words ("minimalist")
  minimalist: ['Less, but better', 'Simply us', 'In this moment', 'Quiet beauty', 'Just enough', 'Stillness'],
  // kept from before — reached only by typed words ("kids")
  kids: ['Oh, the fun we had', 'Little moments, big memories', 'Pure joy', 'Adventure buddies', 'Growing up wild and free', 'Playtime forever'],
  // kept from before — reached only by typed words ("vintage")
  vintage: ['Once upon a time', 'The good old days', 'Timeless memories', 'A moment to remember', 'Made with love, kept forever', 'Some things never fade'],
};

/** Where each public-domain line comes from — the record behind the claim. */
export const PUBLIC_DOMAIN_SOURCES: Record<string, string> = {
  'To have and to hold': 'Book of Common Prayer, marriage vows (1662)',
  'Till death us do part': 'Book of Common Prayer, marriage vows (1662)',
  'For better, for worse': 'Book of Common Prayer, marriage vows (1662)',
  'To love and to cherish': 'Book of Common Prayer, marriage vows (1662)',
  'Grow old along with me! The best is yet to be': 'Robert Browning, Rabbi Ben Ezra (1864)',
  'Love is patient and is kind': '1 Corinthians 13:4, World English Bible',
  'Love never fails': '1 Corinthians 13:8, World English Bible',
  'Two are better than one': 'Ecclesiastes 4:9, King James Version',
  'A threefold cord is not quickly broken': 'Ecclesiastes 4:12, King James Version',
  'Whither thou goest, I will go': 'Ruth 1:16, King James Version',
  'Set me as a seal upon thine heart': 'Song of Solomon 8:6, King James Version',
  'Many waters cannot quench love': 'Song of Solomon 8:7, King James Version',
  'I am my beloved\'s, and my beloved is mine': 'Song of Solomon 6:3, King James Version',
  'How do I love thee? Let me count the ways': 'Elizabeth Barrett Browning, Sonnet 43 (1850)',
  'Come live with me and be my love': 'Christopher Marlowe, The Passionate Shepherd to His Love (1599)',
  'What therefore God hath joined together': 'Mark 10:9, King James Version',
  'My bounty is as boundless as the sea': 'Shakespeare, Romeo and Juliet, Act 2 Scene 2 (1597)',
  'Something old, something new': 'Traditional English wedding rhyme (19th c.)',
  'Something borrowed, something blue': 'Traditional English wedding rhyme (19th c.)',
  'Suffer the little children to come unto me': 'Mark 10:14, King James Version',
  'For of such is the kingdom of God': 'Mark 10:14, King James Version',
  'The Lord bless thee, and keep thee': 'Numbers 6:24, King James Version',
  'The Lord make his face shine upon thee': 'Numbers 6:25, King James Version',
  'I have called thee by thy name; thou art mine': 'Isaiah 43:1, King James Version',
  'For he shall give his angels charge over thee': 'Psalm 91:11, King James Version',
  'The Lord is my shepherd; I shall not want': 'Psalm 23:1, King James Version',
  'Ye are the light of the world': 'Matthew 5:14, King James Version',
  'Let your light so shine before men': 'Matthew 5:16, King James Version',
  'Born of water and of the Spirit': 'John 3:5, King James Version',
  'A new heart also will I give you': 'Ezekiel 36:26, King James Version',
  'Peace be unto you': 'John 20:19, King James Version',
  'Thy word is a lamp unto my feet': 'Psalm 119:105, King James Version',
  'The Lord is my light and my salvation': 'Psalm 27:1, King James Version',
  'Lo, I am with you alway': 'Matthew 28:20, King James Version',
  'God is love': '1 John 4:8, King James Version',
  'We love him, because he first loved us': '1 John 4:19, King James Version',
  'Grace upon grace': 'John 1:16, World English Bible',
  'Safe in the arms of Jesus': 'Fanny Crosby, hymn (1868)',
  'Jesus loves me, this I know': 'Anna Bartlett Warner, poem in Say and Seal (1860)',
  'Many happy returns of the day': 'Traditional birthday greeting (18th c.)',
  'With mirth and laughter let old wrinkles come': 'Shakespeare, The Merchant of Venice, Act 1 Scene 1 (1600)',
  'Age is opportunity no less than youth itself': 'Henry Wadsworth Longfellow, Morituri Salutamus (1875)',
  'Gather ye rosebuds while ye may': 'Robert Herrick, To the Virgins, to Make Much of Time (1648)',
  'Laugh, and the world laughs with you': 'Ella Wheeler Wilcox, Solitude (1883)',
  'A merry heart doeth good like a medicine': 'Proverbs 17:22, King James Version',
  'This is the day which the Lord hath made': 'Psalm 118:24, King James Version',
  'So teach us to number our days': 'Psalm 90:12, King James Version',
  'Monday\'s child is fair in face': 'Traditional rhyme, A. E. Bray, Traditions of Devonshire (1838)',
  'Live while you live': 'Philip Doddridge, epigram on Dum vivimus, vivamus (18th c.)',
  'For this child I prayed': '1 Samuel 1:27, King James Version',
  'Lo, children are an heritage of the Lord': 'Psalm 127:3, King James Version',
  'I am fearfully and wonderfully made': 'Psalm 139:14, King James Version',
  'Before I formed thee in the belly I knew thee': 'Jeremiah 1:5, King James Version',
  'Twinkle, twinkle, little star': 'Jane Taylor, The Star, in Rhymes for the Nursery (1806)',
  'Rock-a-bye baby, on the treetop': 'Traditional nursery rhyme (Mother Goose\'s Melody, c. 1765)',
  'Out of the everywhere into here': 'George MacDonald, Baby, in At the Back of the North Wind (1871)',
  'Heaven lies about us in our infancy': 'William Wordsworth, Intimations of Immortality (1807)',
  'Trailing clouds of glory do we come': 'William Wordsworth, Intimations of Immortality (1807)',
  'Sleep, baby, sleep': 'Traditional lullaby, English words by Elizabeth Prentiss (d. 1878)',
  'Star light, star bright': 'Traditional nursery rhyme (in print by 1866)',
  'Sweet dreams, form a shade': 'William Blake, A Cradle Song, Songs of Innocence (1789)',
  'Hitch your wagon to a star': 'Ralph Waldo Emerson, Civilization, in Society and Solitude (1870)',
  'Knowledge is power': 'Proverb, after Francis Bacon\'s Latin, Meditationes Sacrae (1597)',
  'Ad astra per aspera': 'Latin motto: to the stars through difficulties',
  'Wisdom is the principal thing': 'Proverbs 4:7, King James Version',
  'I can do all things through Christ': 'Philippians 4:13, King James Version',
  'Be strong and of a good courage': 'Joshua 1:9, King James Version',
  'Tomorrow to fresh woods, and pastures new': 'John Milton, Lycidas (1638)',
  'To strive, to seek, to find, and not to yield': 'Alfred Tennyson, Ulysses (1842)',
  'Let us, then, be up and doing': 'Henry Wadsworth Longfellow, A Psalm of Life (1838)',
  'Act well your part, there all the honour lies': 'Alexander Pope, An Essay on Man (1734)',
  'The world was all before them': 'John Milton, Paradise Lost (1667)',
  'Home is where the heart is': 'Proverb (19th century)',
  'There\'s no place like home': 'John Howard Payne, Home! Sweet Home!, from the opera Clari (1823)',
  'Mid pleasures and palaces though we may roam': 'John Howard Payne, Home! Sweet Home!, from the opera Clari (1823)',
  'Honour thy father and thy mother': 'Exodus 20:12, King James Version',
  'Children\'s children are the crown of old men': 'Proverbs 17:6, King James Version',
  'Behold, how good and how pleasant it is': 'Psalm 133:1, King James Version',
  'Her children arise up, and call her blessed': 'Proverbs 31:28, King James Version',
  'As for me and my house, we will serve the Lord': 'Joshua 24:15, King James Version',
  'Train up a child in the way he should go': 'Proverbs 22:6, King James Version',
  'Where we love is home': 'Oliver Wendell Holmes Sr., Homesick in Heaven (1872)',
  'The family is one of nature\'s masterpieces': 'George Santayana, The Life of Reason: Reason in Society (1905)',
  'Blood is thicker than water': 'Proverb (in English print by 1789)',
  'Afoot and light-hearted': 'Walt Whitman, Song of the Open Road (1856)',
  'Travel is fatal to prejudice': 'Mark Twain, The Innocents Abroad (1869)',
  'I travel not to go anywhere, but to go': 'Robert Louis Stevenson, Travels with a Donkey (1879)',
  'The world\'s mine oyster': 'Shakespeare, The Merry Wives of Windsor, Act 2 Scene 2 (1623)',
  'The sea! the sea! the open sea!': 'Barry Cornwall, The Sea, in English Songs (1832)',
  'Over the hills and far away': 'Traditional English song (in print by 1728)',
  'The heavens declare the glory of God': 'Psalm 19:1, King James Version',
  'The mountains are calling and I must go': 'John Muir, letter to his sister (1873; published 1924)',
  'A thing of beauty is a joy for ever': 'John Keats, Endymion (1818)',
  'To every thing there is a season': 'Ecclesiastes 3:1, King James Version',
  'Hope is the thing with feathers': 'Emily Dickinson, Hope, Poems: Second Series (1891)',
  'This above all: to thine own self be true': 'Shakespeare, Hamlet, Act 1 Scene 3 (1604)',
  'Beauty is truth, truth beauty': 'John Keats, Ode on a Grecian Urn (1820)',
  'Carpe diem': 'Horace, Odes 1.11 (23 BC)',
  'What\'s past is prologue': 'Shakespeare, The Tempest, Act 2 Scene 1 (1623)',
  'Well done is better than well said': 'Benjamin Franklin, Poor Richard\'s Almanack (1737)',
  'One today is worth two tomorrows': 'Benjamin Franklin, The Way to Wealth (1758)',
  'Rejoice evermore': '1 Thessalonians 5:16, King James Version',
  'In every thing give thanks': '1 Thessalonians 5:18, King James Version',
  'Love all, trust a few, do wrong to none': 'Shakespeare, All\'s Well That Ends Well, Act 1 Scene 1 (1623)',
  'How far that little candle throws his beams!': 'Shakespeare, The Merchant of Venice (1600)',
  'Earth\'s crammed with heaven': 'Elizabeth Barrett Browning, Aurora Leigh, Book VII (1856)',
  'Every hour of the light and dark is a miracle': 'Walt Whitman, Miracles, Leaves of Grass',
  'Joy delights in joy': 'Shakespeare, Sonnet 8 (1609)',
  'All\'s well that ends well': 'Proverb; Shakespeare play title (1605)',
  'Make hay while the sun shines': 'Proverb (in print by 1744)',
  'It was the best of times': 'Charles Dickens, A Tale of Two Cities (1859)',
  'Count your blessings': 'Johnson Oatman Jr., hymn Count Your Blessings (1897)',
};
